name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build_kernels:
    strategy:
      fail-fast: false
      matrix:
        packages: 
          - linux_rpi3
          - linux_rpi5
    runs-on: ubuntu-24.04-arm
    outputs:
      linux_rpi3: ${{ steps.build.outputs.path_linux_rpi3 }}
      linux_rpi5: ${{ steps.build.outputs.path_linux_rpi5 }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Kernel Package
        id : build
        run: |
          nix_store_path=$(nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.packages }} --print-out-paths)
          echo "path_${{ matrix.packages }}=$nix_store_path" >> "$GITHUB_OUTPUT"

  build_packages:
    strategy:
      fail-fast: false
      matrix:
        packages:
          - raspberrypifw
          - raspberrypiWirelessFirmware
    runs-on: ubuntu-24.04-arm
    outputs:
      raspberrypifw: ${{ steps.build.outputs.path_raspberrypifw }}
      raspberrypiWirelessFirmware: ${{ steps.build.outputs.path_raspberrypiWirelessFirmware }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Packages
        id : build
        run: |
          nix_store_path=$(nix --accept-flake-config build .#packages.aarch64-linux.${{ matrix.packages }} --print-out-paths)
          echo "path_${{ matrix.packages }}=$nix_store_path" >> "$GITHUB_OUTPUT"

  build_installers:
    needs: 
      - build_kernels
      - build_packages
    strategy:
      fail-fast: false
      matrix:
        packages:
          - rpi3-installer
          - rpi5-installer
    runs-on: ubuntu-24.04-arm
    outputs:
      rpi3-installer: ${{ steps.build.outputs.path_rpi3-installer }}
      rpi5-installer: ${{ steps.build.outputs.path_rpi5-installer }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Installers
        id : build
        run: |
          nix_store_path=$(nix --accept-flake-config build .#nixosConfigurations.${{ matrix.packages }}.config.system.build.toplevel --print-out-paths)
          echo "path_${{ matrix.packages }}=$nix_store_path" >> "$GITHUB_OUTPUT"

  upload_artifacts:
    needs: 
      - build_kernels
      - build_packages
      - build_installers
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Collect store paths
        run: |
          mkdir -p result-store/store

          echo "#!/bin/bash" > result-store/copy-from-cache.sh
          echo "set -euo pipefail" >> result-store/copy-from-cache.sh
          echo "store_path=\"file://\${PWD}/\$1\"" >> result-store/copy-from-cache.sh

          echo '[ ${{ toJSON(needs.build_kernels.outputs) }}, ${{ toJSON(needs.build_packages.outputs) }}, ${{ toJSON(needs.build_installers.outputs) }} ]' | \
          jq -r '.[] | to_entries[] | .value' | \
          while read -r path; do
            echo "Storing path: ${path}"
            echo "nix copy --no-check-sigs --from \"\${store_path}\" \"${path}\"" >> result-store/copy-from-cache.sh
            nix --accept-flake-config copy --no-check-sigs --to "file://${PWD}/result-store/store" "${path}"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: binary-cache
          path: result-store
          retention-days: 7